### ISSUE TITLE
Inheriting dependencies from workspace

### ISSUE THREAD

**Issue by clearloop** [gear-tech/gear#2359]
### Problem to Solve

Found a fancy [grammer](https://doc.rust-lang.org/cargo/reference/specifying-dependencies.html#inheriting-a-dependency-from-a-workspace) in `Cargo.toml`

```toml
[dependencies]
regex = { workspace = true, features = ["unicode"] }
```

example in wasmtime: https://github.com/bytecodealliance/wasmtime/blob/main/Cargo.toml

### Possible Solution

follow this grammer to sync and clean our dependencies
