### ISSUE TITLE
Inherit versions from workspace for stable packages

### ISSUE THREAD

**Issue by clearloop** [gear-tech/gear#2448]
### Proposal

https://doc.rust-lang.org/cargo/reference/workspaces.html#the-package-table

For example

```toml
[workspace]
version = "0.1.0"
```

```toml
[package]
name = "gstd"
version.workspace = true
```

ref https://github.com/gear-tech/gear/pull/2343
