### ISSUE TITLE
Inherit package meta from workspace

### ISSUE THREAD

**Issue by clearloop** [gear-tech/gear#2614]
### Problem to Solve

some fields of packages are stable for now that we can just inherit them from the workspace

- authors
- edition
- license

ref #2448

### Possible Solution

```toml
[package]
authors.workspace = true
edition.workspace = true
license.workspace = true
```

```toml
[workspace.package]
edition = "2021"
authors = [ "Gear Technologies" ]
license = "GPL-3.0"
```
