### ISSUE TITLE
gear-wasm-builder: Add support for custom nightly toolchain when building contracts

### ISSUE THREAD

**Issue by shamilsan** [gear-tech/gear#2623]
### Problem to Solve

Need to have a possibility to choose a custom nightly toolchain when building smart contracts using `gear-wasm-builder`.

- Using `rust-toolchain.toml` which allows setting toolchain version:
    ```toml
    [toolchain]
    channel = "nightly-2023-03-14"
    targets = [
      "wasm32-unknown-unknown",
    ]
    ```
- Using `+nightly-<date>` in command line with `cargo build`:
    ```shell
    cargo +nightly-2023-03-14 build --release
    ```

### Possible Solution

Use env variables or parse `rust-toolchain.toml` inside `gear-wasm-builder`.
