### ISSUE TITLE
Run ignored tests on CI

### ISSUE THREAD

**Issue by breathx** [gear-tech/gear#2811]
### Problem to Solve

Stress test with fungible token is really time consuming so it's decided to avoid on `make pre-commit` but it should be ruined somehow on CI

### Possible Solution

/ .. /

**Comment by StackOverflowExcept1on** [comment]
We can periodically run tests that are marked as ignored in CI using cron.
```yaml
on:
  schedule:
    - cron: "0 0 * * MON" # At 00:00 on Monday
```
