### ISSUE TITLE
Introduce program scripts in gcli

### ISSUE THREAD

**Issue by clearloop** [gear-tech/gear#3551]
### Problem to Solve

scripts for deploying / initing programs with gcli

### Possible Solution

a command `gcli run` is required

the scripts should be written in a toml file like `scripts.toml`

```toml
# gcli run create
[create]
salt = ""
init-payload = ""
gas-limit = ""
value = ""

# gcli run upload
[upload]
salt = ""
init-payload = ""
gas-limit = ""
value = ""
```

### Notes

This could be useful for #3570
