### ISSUE TITLE
Fix the documentation of gstd on crates.io

### ISSUE THREAD

**Issue by clearloop** [gear-tech/gear#3575]
### Problem to Solve

docs.rs failed to build the docs of `gstd` build logs: https://docs.rs/crate/gstd/1.0.2/builds/1051841, bcz the `document-features` feature https://github.com/gear-tech/gear/blob/master/gstd/src/lib.rs#L32-L35

### Possible Solution

mb we need to provide

```toml
[features]
document-features = ["dep:document-features"]
```

or checkout the reason from the commands that docs.rs building our docs
