### ISSUE TITLE
Filter dependency features in wasm-builder 

### ISSUE THREAD

**Issue by clearloop** [gear-tech/gear#3588]
### Problem

Dependency features are enabled unexpectedly in wasm-builder

location: https://github.com/gear-tech/gear/blob/master/utils/wasm-builder/src/lib.rs#L126

### Steps

Based on demo-ping

```toml
dependencies]
gstd.workspace = true
gcli = { workspace = true, optional = true }

[build-dependencies]
gear-wasm-builder.workspace = true

[features]
debug = ["gstd/debug"]
default = ["std"]
std = [ "gcli" ]
```
while compiling `demo-ping`, feature `gcli` will be enabled

### Relevant Log Output

<details><summary>Click to expand/collapse</summary>
<p>

```
<Paste your log here>
```

</p>
</details>

**Comment by breathx** [comment]
you don't need gcli while compiling wasm
demo-ping goes to native when std, and for dependable lib with wasm bin while not

**Comment by breathx** [comment]
I suppose issue contains no bug and is only misuse of features

**Comment by clearloop** [comment]
> you don't need gcli while compiling wasm demo-ping goes to native when std, and for dependable lib with wasm bin while not

https://github.com/gear-tech/gear/issues/3587

like the feature in this issue, building specified CLI for programs, imo the expected behavior of passing features is like

```toml
[dependencies]
# this converts to a dependency feature automatically
foo = { version = "*", optional = true } 
```

expected behavior:

```
cargo build 

# nested
cargo build --target wasm32-unknown-unknown --no-default-features
```

but got

```
cargo build 

# nested
cargo build --target wasm32-unknown-unknown --no-default-features --features foo
```

**Comment by shamilsan** [comment]
Could you please add more details about the issue?

If you add an optional dependency to the program, a generated Wasm-project's manifest will contain a feature:

```toml
[dependencies.orig-project]
default-features = false
package = "example"
path = "/path/to/orig-crate"

[features]
foo = ["orig-project/foo"]

[lib]
crate-type = ["cdylib"]
name = "example"

[package]
edition = "2021"
name = "example-wasm"
version = "0.1.0"

# ...
```

If you build your program with feature `foo`, it will be propagated to the generated crate:

```bash
cargo b -F foo # Will use `foo` dependency
```

If you add `foo`-feature as a default, it will be propagated by default:

```toml
[features]
default = ["foo"]
```

```bash
cargo b # Will use `foo` dependency
```

Maybe your trouble is caused by Gear examples being built twice: firstly without the `std` feature (Wasms), and secondly with it (rlibs for tests).
