### ISSUE TITLE
`REF` is undefined even it is passed in github action build.js

### ISSUE THREAD

**Issue by clearloop** [gear-tech/gear#3614]
### Problem

https://github.com/gear-tech/gear/actions/runs/7286236014/job/19858315381?pr=3603

### Steps

this seems happen on `A2-mergeongreen` only for now, for the debug logs, it shows the passed env is

```
 env:
    HEAD_SHA: d7c44036305fe78861475ce6ad756dd1bd59e3cd
    LABEL: A2-mergeoncegreen
    REF: cl/sandbox-deps
    TITLE: chore(sandbox): use sp-wasm-interface-common instead of sp-wasm-interface
    NUMBER: 3603
    REPO: gear-tech/gear
```

however, still got

```
TypeError: Cannot read properties of undefined (reading 'startsWith')
    at skip (/home/runner/work/gear/gear/.github/actions/label/build.js:27:28)
```

### Relevant Log Output

<details><summary>Click to expand/collapse</summary>
<p>

```
<Paste your log here>
```

</p>
</details>
