### ISSUE TITLE
Send and expect custom payload in tests

### ISSUE THREAD

**Issue by ukint-vs** [gear-tech/gear#96]
**Problem to Solve**
Custom payload in tests.

**Possible Solution**
Parse metadata from `.meta.wasm` and encode/decode data provided from `.yaml` with SCALE.

**Notes**
Something like this:
```yaml
title: meta

programs:
  - id: 1
    path: examples/target/wasm32-unknown-unknown/release/demo_meta.wasm
    meta: examples/target/wasm32-unknown-unknown/release/demo_meta.meta.wasm
    init_message:
      kind: custom
      value:
        value: 1
        annotation: "hello"

fixtures:
  - title: meta
    messages:
      - destination: 1
        payload:
          kind: custom
          value:
            value: 1
            annotation: "hello"
    expected:
      - messages:
          - destination: 1
            payload:
              kind: custom
              value:
                old_value: 0
                new_value: 1
```
